// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBGqGFiXEWdLOMt52onLhvMagIguwiB4',
    appId: '1:841264048456:web:7e3e4276c7be01128d2b7d',
    messagingSenderId: '841264048456',
    projectId: 'eventproject-e7d6c',
    authDomain: 'eventproject-e7d6c.firebaseapp.com',
    storageBucket: 'eventproject-e7d6c.appspot.com',
    measurementId: 'G-24GHMMECZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg6rfyITzV8rDB4fi_l-Zp5sgy2xRC8FY',
    appId: '1:841264048456:android:45901dc44d0f12d28d2b7d',
    messagingSenderId: '841264048456',
    projectId: 'eventproject-e7d6c',
    storageBucket: 'eventproject-e7d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLeLlQORfrizmZsLtyUG0YGaiTwQ5r-Qc',
    appId: '1:841264048456:ios:33208a5f2a51952b8d2b7d',
    messagingSenderId: '841264048456',
    projectId: 'eventproject-e7d6c',
    storageBucket: 'eventproject-e7d6c.appspot.com',
    iosClientId: '841264048456-celifhdbb6idv809ok9tehm6i3djoh93.apps.googleusercontent.com',
    iosBundleId: 'com.eventproject.app',
  );
}
